-- AlterTable
ALTER TABLE "AMM" ADD COLUMN "isGlobal" BOOLEAN;
ALTER TABLE "AMM" ADD COLUMN "lpSupply" TEXT;
ALTER TABLE "AMM" ADD COLUMN "parallelism" TEXT;
ALTER TABLE "AMM" ADD COLUMN "xName" TEXT;
ALTER TABLE "AMM" ADD COLUMN "yName" TEXT;
